parameters:
#    lewik_user.example.class: Lewik\UserBundle\Example

services:
#    lewik_user.example:
#        class: %lewik_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
