parameters:
#    lewik_system.example.class: Lewik\SystemBundle\Example

services:
#    lewik_system.example:
#        class: %lewik_system.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
