parameters:
#    lewik_page.example.class: Lewik\PageBundle\Example

services:
#    lewik_page.example:
#        class: %lewik_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
